import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "activation/index": "src/activation/index.ts",
    "adapters/index": "src/adapters/index.ts",
    "audit/index": "src/audit/index.ts",
    "db/index": "src/db/index.ts",
    "dream/index": "src/dream/index.ts",
    "eval/index": "src/eval/index.ts",
    "memory/index": "src/memory/index.ts",
    "policy/index": "src/policy/index.ts",
    "plugin/index": "src/plugin/index.ts",
    "bin/harness-memory": "src/bin/harness-memory.ts",
    "cli/adapter-test": "src/cli/adapter-test.ts",
    "cli/dream-evidence-list": "src/cli/dream-evidence-list.ts",
    "cli/dream-extract": "src/cli/dream-extract.ts",
    "cli/dream-run": "src/cli/dream-run.ts",
    "cli/dream-runs-list": "src/cli/dream-runs-list.ts",
    "cli/dream-runs-show": "src/cli/dream-runs-show.ts",
    "cli/eval-baseline": "src/cli/eval-baseline.ts",
    "cli/eval-memory": "src/cli/eval-memory.ts",
    "cli/fixtures-add-conflict": "src/cli/fixtures-add-conflict.ts",
    "cli/fixtures-add-duplicate-memory": "src/cli/fixtures-add-duplicate-memory.ts",
    "cli/fixtures-add-policy-rules": "src/cli/fixtures-add-policy-rules.ts",
    "cli/inspect": "src/cli/inspect.ts",
    "cli/init": "src/cli/init.ts",
    "cli/install": "src/cli/install.ts",
    "cli/memory-add": "src/cli/memory-add.ts",
    "cli/memory-baseline": "src/cli/memory-baseline.ts",
    "cli/memory-demote": "src/cli/memory-demote.ts",
    "cli/memory-export": "src/cli/memory-export.ts",
    "cli/memory-export-skill": "src/cli/memory-export-skill.ts",
    "cli/memory-history": "src/cli/memory-history.ts",
    "cli/memory-list": "src/cli/memory-list.ts",
    "cli/memory-promote": "src/cli/memory-promote.ts",
    "cli/memory-reject": "src/cli/memory-reject.ts",
    "cli/memory-review": "src/cli/memory-review.ts",
    "cli/memory-stats": "src/cli/memory-stats.ts",
    "cli/memory-why": "src/cli/memory-why.ts",
    "cli/migrate": "src/cli/migrate.ts",
    "cli/policy-check": "src/cli/policy-check.ts",
  },
  format: ["esm"],
  target: "node18",
  platform: "node",
  bundle: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  dts: true,
  shims: false,
  outDir: "dist",
  external: ["sql.js", "@xenova/transformers", "@opencode-ai/sdk"],
});
